### ISSUE TITLE
How can I get the best inlier correspondences?

### ISSUE THREAD

**Issue by whu-lyh** [WPC-WHU/GROR#6]
Thanks  pengcheng, any idea that I can obtain the inlier correspondences of the best estimation?

**Comment by WPC-WHU** [comment]
Thanks for your attention,you can try the following code to get inliers:
pcl::CorrespondencesPtr est_inliers;
gror.getInlierCorrespondences(est_inliers),

**Comment by whu-lyh** [comment]
Thanks！
